name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Prepare Environment
        run: make reset
      - name: Run Tests
        run: make testacc