name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with: { go-version-file: 'go.mod' }
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.3.3
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('docker-compose.yml') }}
      - name: Prepare Environment
        run: make reset
      - name: Run Tests
        run: make testacc
